# Generated by Django 2.0.3 on 2021-09-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name_bangla', models.CharField(max_length=230)),
                ('district_name_english', models.CharField(max_length=230)),
                ('ordering', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpazillaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upazilla_name_bangla', models.CharField(max_length=230)),
                ('upazilla_name_english', models.CharField(max_length=230)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.DistrictEntry')),
            ],
        ),
    ]
