# Generated by Django 2.0.3 on 2021-09-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=230)),
                ('last_name', models.CharField(max_length=230)),
                ('father_name', models.CharField(max_length=230)),
                ('mother_name', models.CharField(max_length=230)),
                ('date_of_birth', models.CharField(max_length=230)),
                ('national_id', models.CharField(max_length=230)),
                ('pasport_id', models.CharField(max_length=230)),
                ('birth_reg', models.CharField(max_length=230)),
                ('user_name', models.CharField(max_length=230)),
                ('email', models.CharField(max_length=230)),
                ('password', models.CharField(max_length=230)),
                ('present_address', models.CharField(max_length=230)),
                ('present_district', models.CharField(max_length=230)),
                ('present_upazila', models.CharField(max_length=230)),
                ('present_post', models.CharField(max_length=230)),
                ('present_post_code', models.CharField(max_length=230)),
                ('mobile', models.CharField(max_length=230)),
                ('permanent_address', models.CharField(max_length=230)),
                ('permanent_district', models.CharField(max_length=230)),
                ('permanent_upazila', models.CharField(max_length=230)),
                ('permanent_post', models.CharField(max_length=230)),
                ('permanent_post_code', models.CharField(max_length=230)),
                ('ssc_roll', models.CharField(max_length=230)),
                ('ssc_year', models.CharField(max_length=230)),
                ('ssc_group', models.CharField(max_length=230)),
                ('hsc_roll', models.CharField(max_length=230)),
                ('hsc_year', models.CharField(max_length=230)),
                ('hsc_group', models.CharField(max_length=230)),
                ('versity_roll', models.CharField(max_length=230)),
                ('versity_year', models.CharField(max_length=230)),
                ('versity_duration', models.CharField(max_length=230)),
                ('company_name1', models.CharField(max_length=230)),
                ('company_business1', models.CharField(max_length=230)),
                ('company_designation1', models.CharField(max_length=230)),
                ('company_department1', models.CharField(max_length=230)),
                ('company_responsibility1', models.CharField(max_length=230)),
                ('company_emp_time1', models.CharField(max_length=230)),
                ('company_location1', models.CharField(max_length=230)),
                ('company_experience1', models.CharField(max_length=230)),
                ('company_name2', models.CharField(max_length=230)),
                ('company_business2', models.CharField(max_length=230)),
                ('company_designation2', models.CharField(max_length=230)),
                ('company_department2', models.CharField(max_length=230)),
                ('company_responsibility2', models.CharField(max_length=230)),
                ('company_emp_time2', models.CharField(max_length=230)),
                ('company_location2', models.CharField(max_length=230)),
                ('company_experience2', models.CharField(max_length=230)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('same_as_present', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='hscBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='sscBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reletion_status', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Versity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versity_name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VersitySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.Gender'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hsc_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.hscBoard'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.Nationality'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='reletion_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.Status'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.Religion'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ssc_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.sscBoard'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='versity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.Versity'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='versity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.VersitySubject'),
        ),
    ]
