# Generated by Django 2.0.3 on 2021-10-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0004_auto_20211006_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_name',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='vacency',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='workplace',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
