# Generated by Django 2.0.3 on 2021-10-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_auto_20211009_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='category',
            new_name='category_name',
        ),
    ]
