# Generated by Django 2.0.3 on 2021-10-10 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0008_auto_20211009_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='additional_requirment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='education_requirment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience_requirment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_context',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='other_benifit_requirment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
