# Generated by Django 2.0.3 on 2021-10-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0009_auto_20211010_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_salary', models.CharField(blank=True, max_length=230, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvapp.applicant')),
                ('jobpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvapp.jobpost')),
            ],
        ),
    ]
