# Generated by Django 2.0.3 on 2021-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0010_user_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='email',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='password',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
