# Generated by Django 2.0.3 on 2021-10-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0011_auto_20211011_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=230, null=True)),
                ('password', models.CharField(blank=True, max_length=230, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='password',
        ),
    ]
