# Generated by Django 2.0.3 on 2021-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0012_auto_20211014_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='hsc_result',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.FileField(blank=True, upload_to='cv-image/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ssc_result',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='versity_result',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
