# Generated by Django 2.0.3 on 2021-10-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0014_jobpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_application',
            name='shortlist',
            field=models.BooleanField(default=False),
        ),
    ]
