# Generated by Django 2.0.3 on 2021-10-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0015_user_application_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_application',
            name='interviewlist',
            field=models.BooleanField(default=False),
        ),
    ]
